version: "3"

services:
  apache:
    build:
      context: .
    container_name: desafio-growdev
    restart: always
    ports:
      - "8003:8003"
    volumes:
      - ./:/var/www/html/
    depends_on:
      - mysqldb
    links:
      - mysqldb
    networks:
      - laravel

  mysqldb:
    container_name: mysqlASW_2
    image: mysql:5.7
    platform: linux/amd64
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel
    networks:
      - laravel
networks:
  laravel:
    driver: bridge
